QuanlyCV/Models/ManagerZone.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerZone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManagerZone()
        {
            this.SetPermissions = new HashSet<SetPermission>();
        }
    
        public int ManagerZoneId { get; set; }
        public string ManagerZoneName { get; set; }
        public int ManagerZoneStatus { get; set; }
        public string DisplayNameController { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SetPermission> SetPermissions { get; set; }
    }
}

QuanlyCV/Controllers/ManagerZonesController.cs
using QuanlyCV.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanlyCV.Controllers
{
    [AuthorizePermissions]
    public class ManagerZonesController : Controller
    {
        WorkManagermentEntities db = new WorkManagermentEntities();
        // GET: ManagerZones
        public PartialViewResult Index()
        {
            if(Session["EmployeeId"] != null)
            {
                var lstManagerZones = db.ManagerZones.ToList();
                return PartialView(lstManagerZones);
            }else
            {
                return PartialView();
            }
            
        }

        public ActionResult Create()
        {
            try
            {
                ReflectionController reflectionController = new ReflectionController();
                List<Type> lstController = reflectionController.GetController("QuanlyCV");
                List<string> listCurrentController = db.ManagerZones.Select(c => c.ManagerZoneName).ToList();
                foreach (var item in lstController)
                {
                    if (!listCurrentController.Contains(item.Name)){
                        ManagerZone m = new ManagerZone();
                        m.ManagerZoneName = item.Name;
                        m.ManagerZoneStatus = 1;
                        db.ManagerZones.Add(m);
                    }
                }
                db.SaveChanges();
                //TempData["error"] = "Thêm mới thành công";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex;
                return RedirectToAction("Index");
                throw;
            }
        }

        public PartialViewResult ViewUpdate(int id)
        {
            ManagerZone m = db.ManagerZones.Find(id);
            return PartialView(m);
        }
        [HttpPost]
        public ActionResult Update(ManagerZone m)
        {
            try
            {
                db.Entry(m).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["error"] = "cập nhật thành công";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["error"] = "cập nhật không thành công";
                return View();
                throw;
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                ManagerZone m = db.ManagerZones.Find(id);
                m.ManagerZoneStatus = 2;
                db.Entry(m).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["error"] = "Xóa thành công";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                TempData["error"] = "Xóa không thành công";
                return View();
                throw;
            }
        }
    }
}

QuanlyCV/Views/ManagerZones/Index.cshtml
@model IEnumerable<QuanlyCV.Models.ManagerZone>
<div class="main-grid">
    <div class="agile-grids">
        <!-- tables -->

        <div class="table-heading">
            <h2>Danh Sách Khu vực</h2>
            <h4 style="color:darkred">@TempData["error"]</h4>
        </div>
        <a onclick="createManagerZones(this)"><img src="~/Content/images/add-member-icon-32.png" /></a>
        <a onclick="GoToPermissions(this)" class="text-right">Các Quyền</a>
        <div class="agile-tables">
            <div class="w3l-table-info">
                <table id="table">
                    <thead>
                        <tr>
                            <th class="text-center">STT</th>
                            <th class="text-center">Tên Khu Vực</th>
                            <th class="text-center">Tên Khu Vực Tiếng Việt</th>
                            <th class="text-center">Trạng Thái</th>
                            <th class="text-center">Thao Tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{ var stt = 1; }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@stt</td>
                                <td>@item.ManagerZoneName</td>
                                <td>@item.DisplayNameController</td>
                                <td>
                                    @if (item.ManagerZoneStatus == 1)
                                    {
                                        <i class="fa fa-check" style="font-size: 20px; color: green;">Đang bật</i>
                                    }
                                    else
                                    {

                                        <i class="fa fa-times" style="font-size: 20px; color: red;">Đang tắt</i>
                                    }
                                </td>
                                <td class="text-center">
                                    <ul style="display: flex; flex-direction: row; list-style: none; justify-content: center;">
                                        <li><a onclick="ViewUpdateManagerZone(this)" data-id="@item.ManagerZoneId" title="Chi tiết"><img src="~/Content/images/detail-icon-24.png" alt="Chi tiết" class="img-responsive"></a></li>
                                        <li><a onclick="DeleteManagerZone(this)" data-id="@item.ManagerZoneId" title="Xóa"><img src="~/Content/images/delete-icon-24.png" alt="xóa"></a></li>
                                    </ul>
                                </td>
                            </tr>
                            stt++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- //tables -->
    </div>
</div>

QuanlyCV/Views/ManagerZones/Update.cshtml
@model QuanlyCV.Models.ManagerZone
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-grid">
    <div class="agile-grids">
        <!-- input-forms -->
        <div class="grids">
            <div class="progressbar-heading grids-heading">
                <h2>Sửa Thông Tin Chức Vụ</h2>
                <h4 style="color:darkred">@TempData["error"]</h4>
            </div>
            <div class="panel panel-widget forms-panel">
                <div class="forms">
                    <div class="form-grids widget-shadow" data-example-id="basic-forms">
                        <div class="form-title">
                            <h4>Sửa Thông Tin Chức Vụ</h4>
                        </div>
                        <div class="form-body">
                            <form action="@Url.Action("Update","ManagerZones")" method="post">
                                <input type="hidden" name="ManagerZoneId" id="ManagerZoneId" value="@Model.ManagerZoneId" />
                                <div class="form-group">
                                    <label for="ManagerZoneName">Tên chức vụ</label>
                                    <input type="text" name="ManagerZoneName" class="form-control" id="ManagerZoneName" placeholder="Tên chức vụ" required value="@Model.ManagerZoneName">
                                </div>
                                <div class="form-group">
                                    <label for="ManagerZoneStatus">Trạng thái</label>
                                    <select name="ManagerZoneStatus" class="form-control">
                                        <option value="1" @(Model.ManagerZoneStatus == 1 ? "selected" : "")>Kích hoạt</option>
                                        <option value="2" @(Model.ManagerZoneStatus == 2 ? "selected" : "")>Không kích hoạt</option>
                                    </select>
                                </div>

                                <button type="submit" class="btn btn-default w3ls-button">Cập nhật</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- //input-forms -->
    </div>
</div>

QuanlyCV/Views/ManagerZones/ViewUpdate.cshtml
@model QuanlyCV.Models.ManagerZone
@{
    ViewBag.Title = "ViewUpdate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-grid">
    <div class="agile-grids">
        <!-- input-forms -->
        <div class="grids">
            <div class="progressbar-heading grids-heading">
                <h2>Sửa Khu Vực</h2>
                <h4 style="color:darkred">@TempData["error"]</h4>
            </div>
            <div class="panel panel-widget forms-panel">
                <div class="forms">
                    <div class="form-grids widget-shadow" data-example-id="basic-forms">
                        <div class="form-title">
                            <h4>Sửa Khu vực</h4>
                            <a onclick="BackManagerZones(this)">Quay Về</a>
                        </div>
                        <div class="form-body">
                            <form  method="post" onsubmit="UpdateManagerZones(event)">
                                <input type="hidden" name="ManagerZoneId" id="ManagerZoneIdManagerZones" value="@Model.ManagerZoneId" />
                                <div class="form-group">
                                    <label for="ManagerZoneName">Tên Khu Vực</label>
                                    <input type="hidden" name="ManagerZoneName" class="form-control" id="ManagerZoneNameManagerZones" placeholder="Tên chức vụ" value="@Model.ManagerZoneName">
                                    <input type="text" name="" class="form-control" id="" placeholder="Tên chức vụ" disabled value="@Model.ManagerZoneName">
                                </div>
                                <div class="form-group">
                                    <label for="ManagerZoneName">Tên Khu Vực Tiếng Việt</label>
                                    <input type="text" name="DisplayNameController" class="form-control" id="DisplayNameControllerManagerZones" placeholder="Tên chức vụ" value="@Model.DisplayNameController">
                                </div>
                                <div class="form-group">
                                    <label for="ManagerZoneStatus">Trạng thái</label>
                                    <select name="ManagerZoneStatus" id="ManagerZoneStatusManagerZones" class="form-control">
                                        <option value="1" @(Model.ManagerZoneStatus == 1 ? "selected" : "")>Hiển Thị</option>
                                        <option value="2" @(Model.ManagerZoneStatus == 2 ? "selected" : "")>Không Hiển Thị</option>
                                    </select>
                                </div>

                                <button type="submit" class="btn btn-default w3ls-button">Cập nhật</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- //input-forms -->
    </div>
</div>