QuanlyCV/Models/TimeLine.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanlyCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeLine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeLine()
        {
            this.Shares = new HashSet<Share>();
            this.TimeLineDetails = new HashSet<TimeLineDetail>();
        }
    
        public int TimeLineId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int TimeLineStatus { get; set; }
        public string TimeLineDescription { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Share> Shares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeLineDetail> TimeLineDetails { get; set; }
    }
}

QuanlyCV/Controllers/TimeLineController.cs
using QuanlyCV.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanlyCV.Controllers
{
    //[AuthorizePermissions]
    public class TimeLineController : Controller
    {
        private WorkManagermentEntities db = new WorkManagermentEntities();
        public ActionResult Index()
        {
            if (Session["EmployeeId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            int employeeId = (int)Session["EmployeeId"];
            TimeLine t = db.TimeLines.SingleOrDefault(x => x.EmployeeId == employeeId);
            ViewBag.TimeLineDetail = db.sp_GetAllTimeLineDetail(employeeId).ToList();
            var  n = db.Notes.Where(x => x.EmployeeId == employeeId).ToList();
            ViewBag.NoteEmployee = n;
            var tl = db.sp_getEmployeeByTimeLine(employeeId).ToList();
            ViewBag.Timeline = tl;
            var like = db.sp_getAllEmployeeLikeTimeLineDetail().ToList();
            ViewBag.LikeTimeline = like;
            ViewBag.EmployeeId = employeeId;
            var lstComment = db.sp_getAllCommentByTimeLineId(t.TimeLineId).ToList();
            ViewBag.lstCommentByGroup = lstComment;
            ViewBag.Employee = db.Employees.Find(employeeId);
            return View();
        }

        [HttpPost]
        public ActionResult Create(TimeLineDetailModel timeLineDetailModel, HttpPostedFileBase TimeLineImage)
        {
            if (Session["EmployeeId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            int timeLineId = (int)Session["EmployeeId"];
            var nowDate = DateTime.Now;
            TimeLineDetail timeLineDetail = new TimeLineDetail();
            timeLineDetail.TimeLineDetailContent = timeLineDetailModel.TimeLineDetailContent;
            timeLineDetail.TimeLineDetailPostedTime = nowDate;
            timeLineDetail.TimeLineId = timeLineId;
            timeLineDetail.TimeLineDetailType = timeLineDetailModel.TimeLineDetailType;
            timeLineDetail.TimeLineDetailStatus = 1;
            db.TimeLineDetails.Add(timeLineDetail);

            //foreach (HttpPostedFileBase file in TimeLineImage)
            //{  
            if (TimeLineImage != null)
            {
                TimeLineImage timeLineImage = new TimeLineImage();
                timeLineImage.TimeLineDetailId = timeLineDetail.TimeLineDetailId;
                var InputFileName = Path.GetFileName(TimeLineImage.FileName);
                var ServerSavePath = Path.Combine(Server.MapPath("~/Content/Uploads/timelines"), InputFileName);
                TimeLineImage.SaveAs(ServerSavePath);
                timeLineImage.TimeLineImages = InputFileName;
                timeLineImage.TimeLineImageStatus = 1;
                db.TimeLineImages.Add(timeLineImage);
                db.SaveChanges();
            }else
            {
                TimeLineImage timeLineImage = new TimeLineImage();
                timeLineImage.TimeLineDetailId = timeLineDetail.TimeLineDetailId;
                timeLineImage.TimeLineImages = "1";
                timeLineImage.TimeLineImageStatus = 1;
                db.TimeLineImages.Add(timeLineImage);
                db.SaveChanges();
            }
            //}
            return RedirectToAction("Index");
        }
        [HttpPost]
        public bool updateTimelineDescription(string content)
        {
            try
            {
                int employeeId = (int)Session["EmployeeId"];
                TimeLine tl = db.TimeLines.SingleOrDefault(x => x.EmployeeId == employeeId);
                tl.TimeLineDescription = content;
                db.Entry(tl).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return true;
            }
            catch (Exception ex)
            {
                return false;
                throw;
            }
        }
        [HttpPost]
        public PartialViewResult LikeTimeLineDetail(int id)
        {
            try
            {
                int idEmployee = (int)Session["EmployeeId"];
                Like like = db.Likes.SingleOrDefault(x => x.TimeLineDetailId == id && x.EmployeeId == idEmployee);
                if(like != null)
                {
                    like.LikeStatus = 1;
                    db.Entry(like).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                else
                {
                    Like l = new Like();
                    l.TimeLineDetailId = id;
                    l.LikeStatus = 1;
                    l.EmployeeId = idEmployee;
                    l.EmotionId = 1;
                    db.Likes.Add(l);
                    db.SaveChanges();
                }
                var lstLike = db.sp_getAllEmployeeLikeTimeLineDetailByDetailId(id).ToList();
                ViewBag.listLike = lstLike;
                return PartialView();
            }
            catch (Exception ex)
            {
                return PartialView();
                throw;
            }
        }
        [HttpPost]
        public PartialViewResult unLikeTimeDetail(int id)
        {
            try
            {
                int idEmployee = (int)Session["EmployeeId"];
                Like like = db.Likes.SingleOrDefault(x => x.TimeLineDetailId == id && x.EmployeeId == idEmployee);
                like.LikeStatus = 2;
                db.Entry(like).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                var lstLike = db.sp_getAllEmployeeLikeTimeLineDetailByDetailId(id).ToList();
                ViewBag.listLike = lstLike;
                return PartialView();
            }
            catch (Exception ex)
            {
                return PartialView();
                throw;
            }
        }
        public PartialViewResult CommentTimeLineDetail(int id ,string content)
        {
            try
            {
                int employeeId = (int)Session["EmployeeId"];
                Comment m = new Comment();
                m.CommentContent = content;
                m.ParentId = 0;
                m.CommentImage = id + content;
                m.TimeLineDetailId = id;
                m.EmployeeId = employeeId;
                m.CommentTime = DateTime.Now;
                m.CommentStatus = 1;
                db.Comments.Add(m);
                db.SaveChanges();
                ViewBag.listCommentlstTimeLineDetail = db.sp_getAllCommentByTimelineDetailId(id).ToList();
                ViewBag.Employee = db.Employees.Find(employeeId);
                return PartialView();
            }
            catch (Exception ex)
            {
                return PartialView();
                throw;
            }
        }
        public PartialViewResult SubCommentTimeLineDetail(int id, string content, int CommentId)
        {
            try
            {
                int employeeId = (int)Session["EmployeeId"];
                Comment m = new Comment();
                m.CommentContent = content;
                m.ParentId = CommentId;
                m.CommentImage = id + content;
                m.TimeLineDetailId = id;
                m.EmployeeId = employeeId;
                m.CommentTime = DateTime.Now;
                m.CommentStatus = 1;
                db.Comments.Add(m);
                db.SaveChanges();
                ViewBag.listCommentlstTimeLineDetail = db.sp_getAllCommentByTimelineDetailId(id).ToList();
                ViewBag.Employee = db.Employees.Find(employeeId);
                return PartialView();
            }
            catch (Exception ex)
            {
                return PartialView();
                throw;
            }
        }

    }
}

QuanlyCV/Views/TimeLine/CommentTimeLineDetail.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Đăng nhập website quản lý công việc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <link href="~/Content/css/style.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/Content/css/font.css" type="text/css" />
    <link href="~/Content/css/font-awesome.css" rel="stylesheet">
</head>
<body class="signup-body">
    @foreach (var lstComment in ViewBag.listCommentlstTimeLineDetail)
    {
        if (lstComment.ParentId == 0)
        {
            <div class="comment-item comment-post">

                <div class="comment-avatar">
                    <img src="~/Content/images/avatar/@lstComment.EmployeeAvatar" class="img-responsive" alt="avatar">
                </div>
                <div class="comment-content">

                    <div class="">
                        <a href="" class="a-hover-underline coment-content-fullname">@lstComment.EmployeeFullname</a>
                        <span class="coment-content-text">@lstComment.CommentContent</span>
                    </div>
                    <div class="comment-content-action">
                        <a class="a-hover-pointer a-hover-underline">Thích</a>
                        <a class="a-hover-pointer a-hover-underline">Bình luận</a>
                    </div>
                </div>
            </div>

            foreach (var lstComment1 in ViewBag.listCommentlstTimeLineDetail)
            {
                if (lstComment1.ParentId == lstComment.CommentId)
                {
                    <ul class="comment-level-2">
                        <li>
                            <div class="comment-item lst-SubComment-Post-@lstComment.TimeLineDetailId">

                                <div class="comment-avatar">
                                    <img src="~/Content/images/avatar/@lstComment1.EmployeeAvatar" class="img-responsive" alt="avatar">
                                </div>
                                <div class="subcomment-content-post">
                                    <div>
                                        <a href="" class="a-hover-underline coment-content-fullname">@lstComment1.EmployeeFullname</a>
                                        <span class="coment-content-text">@lstComment1.CommentContent</span>
                                    </div>
                                    <div class="comment-content-action">
                                        <a class="a-hover-pointer a-hover-underline">Thích</a>
                                        <a class="a-hover-pointer a-hover-underline">Bình luận</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                }

            }
            <div class="wrapper-input-comment" style="margin-left: 60px;">
                <img src="~/Content/images/avatar/@ViewBag.Employee.EmployeeAvatar" class="img-responsive" alt="">
                <div class="input-comment">
                    <textarea name="" rows="1" onkeyup="textAreaAdjust(this)" class="Content-SubComment-TimeLineDetail-@lstComment.CommentId" style="overflow:hidden"></textarea>
                    <ul class="input-comment-level-2-icon">
                        <li><a class="a-hover-pointer"><i class="fa fa-smile-o"></i></a></li>
                        <li><a class="a-hover-pointer"><i class="fa fa-picture-o"></i></a></li>
                        <li><a class="a-hover-pointer" data-id="@lstComment.TimeLineDetailId" data-content="@lstComment.CommentId" onclick="submitSubCommentTimeLineDetail(this)"><i class="fa fa-paper-plane-o"></i></a></li>
                    </ul>
                </div>
            </div>
        }
    }
    <script>
        function submitSubCommentTimeLineDetail(e) {
            var TimeLineDetailId = $(e).data("id");
            var CommentId = $(e).data("content");
            var content = $(".Content-SubComment-TimeLineDetail-" + CommentId).val();
            alert(content );

            $.ajax({
                type: "POST",
                url: "@Url.Action("SubCommentTimeLineDetail", "TimeLine")",
                data: { id: TimeLineDetailId, content: content, CommentId: CommentId },
            success: function (rps) {
                $(".lst-Comment-TimeLineDetail-" + TimeLineDetailId).html(rps);
            }
        });
            $(".Content-SubComment-TimeLineDetail-" + CommentId).val("");
        }
    </script>
    </body>
</html>

QuanlyCV/Views/TimeLine/LikeTimeLineDetail.cshtml
<img src="~/Content/images/facebook-like-icon.png" class="img-responsive" alt="like">
@foreach (var item in ViewBag.listLike)
{
    <a class="a-hover-pointer a-hover-underline list-like"> @item.EmployeeFullname, </a>
}

QuanlyCV/Views/TimeLine/SubCommentTimeLineDetail.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Đăng nhập website quản lý công việc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <link href="~/Content/css/style.css" rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="~/Content/css/font.css" type="text/css" />
    <link href="~/Content/css/font-awesome.css" rel="stylesheet">
</head>
<body class="signup-body">
    @foreach (var lstComment in ViewBag.listCommentlstTimeLineDetail)
    {

        if (lstComment.ParentId == 0)
        {
            <div class="comment-item comment-post">

                <div class="comment-avatar">
                    <img src="~/Content/images/avatar/@lstComment.EmployeeAvatar" class="img-responsive" alt="avatar">
                </div>
                <div class="comment-content">

                    <div class="">
                        <a href="" class="a-hover-underline coment-content-fullname">@lstComment.EmployeeFullname</a>
                        <span class="coment-content-text">@lstComment.CommentContent</span>
                    </div>
                    <div class="comment-content-action">
                        <a class="a-hover-pointer a-hover-underline">Thích</a>
                        <a class="a-hover-pointer a-hover-underline">Bình luận</a>
                    </div>
                </div>
            </div>

            foreach (var lstComment1 in ViewBag.listCommentlstTimeLineDetail)
            {
                if (lstComment1.ParentId == lstComment.CommentId)
                {
                    <ul class="comment-level-2">
                        <li>
                            <div class="comment-item lst-SubComment-Post-@lstComment.TimeLineDetailId">

                                <div class="comment-avatar">
                                    <img src="~/Content/images/avatar/@lstComment1.EmployeeAvatar" class="img-responsive" alt="avatar">
                                </div>
                                <div class="subcomment-content-post">
                                    <div>
                                        <a href="" class="a-hover-underline coment-content-fullname">@lstComment1.EmployeeFullname</a>
                                        <span class="coment-content-text">@lstComment1.CommentContent</span>
                                    </div>
                                    <div class="comment-content-action">
                                        <a class="a-hover-pointer a-hover-underline">Thích</a>
                                        <a class="a-hover-pointer a-hover-underline">Bình luận</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                }

            }
            <div class="wrapper-input-comment" style="margin-left: 60px;">
                <img src="~/Content/images/avatar/@ViewBag.Employee.EmployeeAvatar" class="img-responsive" alt="">
                <div class="input-comment">
                    <textarea name="" rows="1" onkeyup="textAreaAdjust(this)" class="Content-SubComment-TimeLineDetail-@lstComment.CommentId" style="overflow:hidden"></textarea>
                    <ul class="input-comment-level-2-icon">
                        <li><a class="a-hover-pointer"><i class="fa fa-smile-o"></i></a></li>
                        <li><a class="a-hover-pointer"><i class="fa fa-picture-o"></i></a></li>
                        <li><a class="a-hover-pointer" data-id="@lstComment.TimeLineDetailId" data-content="@lstComment.CommentId" onclick="submitSubCommentTimeLineDetail(this)"><i class="fa fa-paper-plane-o"></i></a></li>
                    </ul>
                </div>
            </div>
        }
    }
    <script>
        function submitSubCommentTimeLineDetail(e) {
            var TimeLineDetailId = $(e).data("id");
            var CommentId = $(e).data("content");
            var content = $(".Content-SubComment-TimeLineDetail-" + CommentId).val();
            alert(CommentId +" - " + content );

            $.ajax({
                type: "POST",
                url: "@Url.Action("SubCommentTimeLineDetail", "TimeLine")",
                data: { id: TimeLineDetailId, content: content, CommentId: CommentId },
            success: function (rps) {
                $(".lst-Comment-TimeLineDetail-" + TimeLineDetailId).html(rps);
            }
        });
        $(".Content-SubComment-TimeLineDetail-" + CommentId).val("");
        }
    </script>
    </body>
</html>

QuanlyCV/Views/TimeLine/unLikeTimeDetail.cshtml
<img src="~/Content/images/facebook-like-icon.png" class="img-responsive" alt="like">
@foreach (var item in ViewBag.listLike)
{
    <a class="a-hover-pointer a-hover-underline list-like"> @item.EmployeeFullname, </a>
}