QuanlyCV/Controllers/InfomationController.cs
using QuanlyCV.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanlyCV.Controllers
{

    public class InfomationController : Controller
    {
        WorkManagermentEntities db = new WorkManagermentEntities();
        // GET: Infomation
        public ActionResult Index()
        {
            try
            {
                if(Session["EmployeeId"] != null)
                {
                    Employee e = db.Employees.Find(Session["EmployeeId"]);
                    ViewBag.Emloyee = e;
                    return View();
                }
                else
                {
                    return RedirectToAction("Index");
                }
                
            }
            catch (Exception)
            {

                throw;
            }
        }
        [HttpPost]
        public ActionResult UpdateInfomation(HttpPostedFileBase EmployeeAvatar, HttpPostedFileBase EmployeeCoverPicture,Employee e)
        {
            try
            {
                if(EmployeeAvatar!= null  && EmployeeCoverPicture != null)
                {
                    string avatarFile = Path.Combine(Server.MapPath("~/Content/images/avatar/"), Path.GetFileName(EmployeeAvatar.FileName));
                    EmployeeAvatar.SaveAs(avatarFile);
                    var avatar = EmployeeAvatar.FileName;
                    string coverPictureFile = Path.Combine(Server.MapPath("~/Content/images/coverPicture/"), Path.GetFileName(EmployeeCoverPicture.FileName));
                    EmployeeCoverPicture.SaveAs(coverPictureFile);
                    var coverPicture = EmployeeCoverPicture.FileName;
                    Employee em = db.Employees.Find(e.EmployeeId);
                    em.EmployeeFullname = e.EmployeeFullname;
                    em.EmployeeBirthday = e.EmployeeBirthday;
                    em.EmployeeIdCard = e.EmployeeIdCard;
                    em.EmployeePhone = e.EmployeePhone;
                    em.EmployeeAddress = e.EmployeeAddress;
                    em.EmployeeEmail = e.EmployeeEmail;
                    em.EmployeePassword = em.EmployeePassword;
                    em.EmployeeAvatar = avatar;
                    em.EmployeeCoverPicture = coverPicture;
                    em.EmployeeStatus = 1;
                    db.Entry(em).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                    TempData["error"] = "cập nhật thành công";
                    return RedirectToAction("Index");
                }else
                {
                    if(EmployeeAvatar != null)
                    {
                        string avatarFile = Path.Combine(Server.MapPath("~/Content/images/avatar/"), Path.GetFileName(EmployeeAvatar.FileName));
                        EmployeeAvatar.SaveAs(avatarFile);
                        var avatar = EmployeeAvatar.FileName;
                        Employee em = db.Employees.Find(e.EmployeeId);
                        em.EmployeeFullname = e.EmployeeFullname;
                        em.EmployeeBirthday = e.EmployeeBirthday;
                        em.EmployeeIdCard = e.EmployeeIdCard;
                        em.EmployeePhone = e.EmployeePhone;
                        em.EmployeeAddress = e.EmployeeAddress;
                        em.EmployeeEmail = e.EmployeeEmail;
                        em.EmployeePassword = em.EmployeePassword;
                        em.EmployeeAvatar = avatar;
                        em.EmployeeCoverPicture = em.EmployeeCoverPicture;
                        em.EmployeeStatus = 1;
                        db.Entry(em).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        TempData["error"] = "cập nhật thành công";
                        return RedirectToAction("Index");
                    }
                    else if(EmployeeCoverPicture != null)
                    {
                        string coverPictureFile = Path.Combine(Server.MapPath("~/Content/images/coverPicture/"), Path.GetFileName(EmployeeCoverPicture.FileName));
                        EmployeeCoverPicture.SaveAs(coverPictureFile);
                        var coverPicture = EmployeeCoverPicture.FileName;
                        Employee em = db.Employees.Find(e.EmployeeId);
                        em.EmployeeFullname = e.EmployeeFullname;
                        em.EmployeeBirthday = e.EmployeeBirthday;
                        em.EmployeeIdCard = e.EmployeeIdCard;
                        em.EmployeePhone = e.EmployeePhone;
                        em.EmployeeAddress = e.EmployeeAddress;
                        em.EmployeeEmail = e.EmployeeEmail;
                        em.EmployeePassword = em.EmployeePassword;
                        em.EmployeeAvatar = em.EmployeeAvatar;
                        em.EmployeeCoverPicture = coverPicture;
                        em.EmployeeStatus = 1;
                        db.Entry(em).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        TempData["error"] = "cập nhật thành công";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        Employee em = db.Employees.Find(e.EmployeeId);
                        em.EmployeeFullname = e.EmployeeFullname;
                        em.EmployeeBirthday = e.EmployeeBirthday;
                        em.EmployeeIdCard = e.EmployeeIdCard;
                        em.EmployeePhone = e.EmployeePhone;
                        em.EmployeeAddress = e.EmployeeAddress;
                        em.EmployeeEmail = e.EmployeeEmail;
                        em.EmployeePassword = em.EmployeePassword;
                        em.EmployeeAvatar = em.EmployeeAvatar;
                        em.EmployeeCoverPicture = em.EmployeeCoverPicture;
                        em.EmployeeStatus = 1;
                        db.Entry(em).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        TempData["error"] = "cập nhật thành công";
                        return RedirectToAction("Index");
                    }
                }
               
            }
            catch (Exception)
            {
                return View();
                throw;
            }
        }
        public ActionResult ViewChangePassword()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(string EmployeePassword,string newpassword,string repeatpassword,int EmployeeId)
        {
            try
            {
                Employee e = db.Employees.Find(EmployeeId);
                if (e != null)
                {
                    var pass = Unti.Utility.getHashedMD5(EmployeePassword);
                    if (e.EmployeePassword.Equals(pass))
                    {
                        if (newpassword.Equals(repeatpassword))
                        {
                            var passNew = Unti.Utility.getHashedMD5(newpassword);
                            e.EmployeePassword = passNew;
                            db.Entry(e).State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();
                            TempData["error"] = "đổi mật khẩu thành công";
                            return RedirectToAction("Index","Home");
                        }
                        else
                        {
                            TempData["error"] = "mật khẩu mới không khớp";
                            return RedirectToAction("ViewChangePassword");
                        }
                    }else
                    {
                        TempData["error"] = "mật khẩu cũ không đúng";
                        return RedirectToAction("ViewChangePassword");
                    }
                }else
                {
                    return RedirectToAction("Index", "Login");
                }
               
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

QuanlyCV/Views/Infomation/ChangePassword.cshtml
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main-grid">
    <div class="agile-grids">
        <!-- input-forms -->
        <div class="grids">
            <div class="progressbar-heading grids-heading">
                <h2>Thay Đổi Mật Khẩu</h2>
            </div>
            <div class="panel panel-widget forms-panel">
                <div class="forms">
                    <div class="form-grids widget-shadow" data-example-id="basic-forms">
                        <div class="form-title">
                            <h4>Thay Đổi Mật Khẩu :</h4>
                            <h5 style="color:darkred">@TempData["error"]</h5>
                        </div>
                        <div class="form-body">
                            <form action="@Url.Action("ChangePassword","Infomation")" method="post">
                            <input type="hidden" name="EmployeeId" id="EmployeeId" value="@Session["EmployeeId"]" />
                                <div class="form-group">
                                    <label for="oldpassword">Mật khẩu cũ</label>
                                    <input type="password" name="EmployeePassword" class="form-control" id="EmployeePassword" placeholder="Mật khẩu cũ" required>
                                </div>
                                <div class="form-group">
                                    <label for="newpassword">Mật khẩu mới</label>
                                    <input type="password" name="newpassword" class="form-control" id="newpassword" placeholder="Mật khẩu mới" required>
                                </div>
                                <div class="form-group">
                                    <label for="repeatpassword">Mật khẩu mới</label>
                                    <input type="password" name="repeatpassword" class="form-control" id="repeatpassword" placeholder="Xác nhận mật khẩu" required>
                                </div>
                                <button type="submit" class="btn btn-default w3ls-button">Xác Nhận</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- //input-forms -->
    </div>
</div>

QuanlyCV/Views/Infomation/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-grid">
    <div class="agile-grids">
        <!-- input-forms -->
        <div class="grids">
            <div class="progressbar-heading grids-heading">
                <h2>Thay Đổi Thông Tin</h2>
            </div>
            <div class="panel panel-widget forms-panel">
                <div class="forms">
                    <div class="form-grids widget-shadow" data-example-id="basic-forms">
                        <div class="form-title">
                            <h4>Thay Đổi Thông Tin :</h4>
                            <h5 style="color:darkred">@TempData["error"]</h5>
                        </div>
                        <div class="form-body">
                            <form action="@Url.Action("UpdateInfomation","Infomation")" method="post" enctype="multipart/form-data">
                                <input type="hidden" id="EmployeeId" name="EmployeeId" value="@Session["EmployeeId"]" />
                                <div class="form-group">
                                    <label for="fullname">Ảnh Đại Diện</label>
                                    <br />
                                    <img width="80" height="80" src="~/Content/images/avatar/@ViewBag.Emloyee.EmployeeAvatar" />
                                    <input type="file" name="EmployeeAvatar" class="form-control" id="EmployeeAvatar" placeholder="Ảnh đại diện">
                                </div>
                                <div class="form-group">
                                    <label for="fullname">Ảnh Bìa</label>
                                    <br />
                                    <img width="1108" height="100" src="~/Content/images/coverPicture/@ViewBag.Emloyee.EmployeeCoverPicture" />
                                    <input type="file" name="EmployeeCoverPicture" class="form-control" id="EmployeeCoverPicture" placeholder="Ảnh đại diện">
                                </div>
                                <div class="form-group">
                                    <label for="fullname">Họ Tên</label>
                                    <input type="text" name="EmployeeFullname" class="form-control" id="EmployeeFullname" placeholder="Họ tên" value="@ViewBag.Emloyee.EmployeeFullname" required>
                                </div>
                                <div class="form-group">
                                    <label for="birthday">Ngày sinh</label>
                                    <input type="date" name="EmployeeBirthday" class="form-control" id="EmployeeBirthday" placeholder="Ngày sinh" value="@ViewBag.Emloyee.EmployeeBirthday.ToString("yyyy-MM-dd")" required>
                                </div>
                                <div class="form-group">
                                    <label for="identitycard">Chứng Minh Thư</label>
                                    <input type="text" name="EmployeeIdCard" class="form-control" id="EmployeeIdCard" placeholder="Chứng minh thư" value="@ViewBag.Emloyee.EmployeeIdCard" required>
                                </div>
                                <div class="form-group">
                                    <label for="phone">Điện thoại</label>
                                    <input type="text" name="EmployeePhone" class="form-control" id="EmployeePhone" placeholder="Số điện thoại" value="@ViewBag.Emloyee.EmployeePhone" required>
                                </div>
                                <div class="form-group">
                                    <label for="address">Địa chỉ</label>
                                    <!-- <input type="text" name="fullname" class="form-control" id="fullname" placeholder="Mật khẩu cũ">  -->
                                    <textarea name="EmployeeAddress" id="EmployeeAddress" placeholder="Địa chỉ" required>@ViewBag.Emloyee.EmployeeAddress</textarea>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="text" name="EmployeeEmail" class="form-control" id="EmployeeEmail" placeholder="Email" value="@ViewBag.Emloyee.EmployeeEmail" required>
                                </div>
                                <button type="submit" class="btn btn-default w3ls-button">Xác Nhận</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- //input-forms -->
    </div>
</div>

QuanlyCV/Views/Infomation/ViewChangePassword.cshtml
@{
    ViewBag.Title = "ViewChangePassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-grid">
    <div class="agile-grids">
        <!-- input-forms -->
        <div class="grids">
            <div class="progressbar-heading grids-heading">
                <h2>Thay Đổi Mật Khẩu</h2>
            </div>
            <div class="panel panel-widget forms-panel">
                <div class="forms">
                    <div class="form-grids widget-shadow" data-example-id="basic-forms">
                        <div class="form-title">
                            <h4>Thay Đổi Mật Khẩu :</h4>
                            <h5 style="color:darkred">@TempData["error"]</h5>
                        </div>
                        <div class="form-body">
                            <form action="@Url.Action("ChangePassword","Infomation")" method="post">
                                <input type="hidden" name="EmployeeId" id="EmployeeId" value="@Session["EmployeeId"]" />
                                <div class="form-group">
                                    <label for="oldpassword">Mật khẩu cũ</label>
                                    <input type="password" name="EmployeePassword" class="form-control" id="EmployeePassword" placeholder="Mật khẩu cũ" required>
                                </div>
                                <div class="form-group">
                                    <label for="newpassword">Mật khẩu mới</label>
                                    <input type="password" name="newpassword" class="form-control" id="newpassword" placeholder="Mật khẩu mới" required>
                                </div>
                                <div class="form-group">
                                    <label for="repeatpassword">Mật khẩu mới</label>
                                    <input type="password" name="repeatpassword" class="form-control" id="repeatpassword" placeholder="Xác nhận mật khẩu" required>
                                </div>
                                <button type="submit" class="btn btn-default w3ls-button">Xác Nhận</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- //input-forms -->
    </div>
</div>