QuanlyCV/Controllers/StatisticalController.cs
using QuanlyCV.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuanlyCV.Controllers
{
    [AuthorizePermissions]
    public class StatisticalController : Controller
    {
        WorkManagermentEntities db = new WorkManagermentEntities();
        public ActionResult Index()
        {
            if (Session["EmployeeId"] != null)
            {
                int id = (int)Session["EmployeeId"];
                DepartmentEmployee de = db.DepartmentEmployees.SingleOrDefault(x => x.EmployeeId == id);
                GrantPermission gp = db.GrantPermissions.SingleOrDefault(x => x.DepartmentEmployeeId == de.DepartmentEmployeeId);
                var pm = db.ProjectMembers.Where(x => x.GrantPermissionId == gp.GrantPermissionId).ToList();
                ViewBag.ProjectMembers = pm;
                var lstProject = db.Projects.Where(x => x.ProjectStatus == 1).ToList();
                var lstDepartments = db.Departments.Where(x => x.DepartmentStatus == 1).ToList();
                ViewBag.listProject = lstProject;
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }

        }

        public PartialViewResult GetAllProjectByYearAndMonth(int? month, int? year)
        {
            try
            {
                int idEmployee = (int)Session["EmployeeId"];
                DepartmentEmployee de = db.DepartmentEmployees.SingleOrDefault(x => x.EmployeeId == idEmployee);
                GrantPermission gp = db.GrantPermissions.SingleOrDefault(x => x.DepartmentEmployeeId == de.DepartmentEmployeeId);
                var pm = db.ProjectMembers.Where(x => x.GrantPermissionId == gp.GrantPermissionId).ToList();
                ViewBag.ProjectMembers = pm;
                if (month == null && year == null)
                {
                    var lstProject = db.Projects.Where(x => x.ProjectStatus == 1).ToList();
                    ViewBag.listProject = lstProject;
                }
                else
                {
                    if (month == null)
                    {
                        var lstProject = db.Projects.Where(x => x.ProjectStatus == 1 && x.StartTime.Year == year).ToList();
                        ViewBag.listProject = lstProject;
                    }
                    else if (year == null)
                    {
                        var lstProject = db.Projects.Where(x => x.ProjectStatus == 1 && x.StartTime.Month == month).ToList();
                        ViewBag.listProject = lstProject;
                    }
                    else
                    {
                        var lstProject = db.Projects.Where(x => x.ProjectStatus == 1 && x.StartTime.Year == year && x.StartTime.Month == month).ToList();
                        ViewBag.listProject = lstProject;
                    }
                }


                return PartialView();

            }
            catch (Exception ex)
            {

                throw;
            }
        }
        public PartialViewResult LoadListEmployeeByProject(int id)
        {
            try
            {
                var lstEmployee = db.Employees.Where(x => x.EmployeeStatus == 1).ToList();
                var lstDepartment = db.Departments.Where(x => x.DepartmentStatus == 1).ToList();
                var lstEmployeeByProjectId = db.sp_GetAllEmployeeByProjectID(id);
                ViewBag.listEmployeeByProjectId = lstEmployeeByProjectId;
                var lstEmployeeByRoleId = db.sp_getAllEmployeeByRoleID(6).ToList();
                ViewBag.listEmployeeByRoleId = lstEmployeeByRoleId;
                return PartialView();
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public PartialViewResult LoadModelDetailWork(int ProjectId,int EmployeeId)
        {
            try
            {
                var DetailEmployeeByWork = db.sp_getAllByProjectIdAndEmployeeId(ProjectId, EmployeeId).ToList();
                ViewBag.DetailEmployeeByWork = DetailEmployeeByWork;
                return PartialView();
            }
            catch (Exception ex)
            {

                throw;
            }
        }
    }
}

QuanlyCV/Views/Statistical/GetAllProjectByYearAndMonth.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Đăng nhập website quản lý công việc</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link rel="stylesheet" type="text/css" href="~/Content/css/lightslider.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/mystyle.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/myfolder.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/myworking.css">
    <script src="~/Scripts/js/jquery2.0.3.min.js"></script>
    <script src="~/Scripts/js/lightslider.js"></script>
    <script src="~/Scripts/js/myscript.js"></script>
</head>
<body>
    <div class="index-slide-jobs">
        <div class="item-slide-job">
            <ul id="content-slider" class="content-slider">
                @foreach (var item1 in ViewBag.ProjectMembers)
            {
                foreach (var item in ViewBag.listProject)
                {
                    if (item1.ProjectId == item.ProjectId)
                    {
                            <li data-id="@item.ProjectId"  onclick="ClickProject(this)">
                                <div class="working-slide-item">
                                    <div class="working-slide-item-name">
                                        <h3>@item.ProjectName</h3>
                                    </div>
                                    <div class="working-slide-item-time">
                                        <span>Thời gian: </span>@item.StartTime.ToString("yyyy-MM-dd") - @item.EndTime.ToString("yyyy-MM-dd")
                                    </div>
                                    @*<div class="working-slide-item-progress">
                                            <p><span>Tiến độ: </span>3/10</p>
                                        </div>*@
                                </div>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
    </div>
    <div class="clearfix"> </div>
    <script>
        $("#content-slider").lightSlider({
            loop: true,
            keyPress: true
        });
        $('#image-gallery').lightSlider({
            gallery: true,
            item: 1,
            thumbItem: 9,
            slideMargin: 0,
            speed: 500,
            auto: true,
            loop: true,
            onSliderLoad: function () {
                $('#image-gallery').removeClass('cS-hidden');
            }
        });
    </script>
</body>
</html>

QuanlyCV/Views/Statistical/Index.cshtml
@{
    ViewBag.Title = "Thống kê";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-grid">
    <div class="div-thanh-trang-thai">
        <div class="social grid">
            <div class="grid-info">
                <div class="col-md-3 top-comment-grid">
                    <a class="a-hover-pointer">
                        <div class="comments likes" onclick="setContentForSlide('.likes');">
                            <div class="comments-icon">
                                <i class="fa fa-calendar-minus-o"></i>
                            </div>
                            <div class="comments-info likes-info">
                                <h3>95K</h3>
                                <span style="color: #6C8CD0;">Đang làm</span>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 top-comment-grid">
                    <a class="a-hover-pointer">
                        <div class="comments comments-bg" onclick="setContentForSlide('.comments-bg');">
                            <div class="comments-icon">
                                <i class="fa fa-hourglass-start"></i>
                            </div>
                            <div class="comments-info">
                                <h3>12K</h3>
                                <span style="color: #FFCC66;">Đang Chậm</span>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 top-comment-grid">
                    <a class="a-hover-pointer">
                        <div class="comments tweets" onclick="setContentForSlide('.tweets');">
                            <div class="comments-icon">
                                <i class="fa fa-clock-o"></i>
                            </div>
                            <div class="comments-info tweets-info">
                                <h3>27K</h3>
                                <span style="color: #ff8888;">Quá Hạn</span>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 top-comment-grid">
                    <a class="a-hover-pointer">
                        <div class="comments views" onclick="setContentForSlide('.views');">
                            <div class="comments-icon">
                                <i class="fa fa-calendar-check-o"></i>
                            </div>
                            <div class="comments-info views-info">
                                <h3>557K</h3>
                                <span style="color: #07CEB0">Hoàn Thành</span>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
        <div>
            <a href="" data-toggle="modal" data-target="#ModalAddNewWork" title="Thêm mới công việc" class="a-chon-ngay-thang">Chọn Tháng</a>
        </div>
        <div class="modal fade" id="ModalAddNewWork" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="display: none;">
            <div class="modal-dialog" role="document">
                <div class="modal-content-add-new-work">
                    <div class="modal-header-add-new-work">
                        <h5 class="modal-title" id="exampleModalLabel" style="float: left; font-weight: bold;">Chọn Tháng</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="" method="post" onsubmit="loadListProject(event)">
                            <div class="form-group">
                                <label style="float: left;" for="recipient-name" class="col-form-label">Chọn Tháng</label>
                                <select name="month" id="month" class="form-control">
                                    <option value=""></option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                </select>
                                <label style="float: left;" for="recipient-name" class="col-form-label">Chọn Năm</label>
                                <select name="year" id="year" class="form-control">
                                    <option value=""></option>
                                    <option value="2013">2013</option>
                                    <option value="2014">2014</option>
                                    <option value="2015">2015</option>
                                    <option value="2016">2016</option>
                                    <option value="2017">2017</option>
                                    <option value="2018">2018</option>
                                    <option value="2019">2019</option>
                                    <option value="2020">2020</option>
                                    <option value="2021">2021</option>
                                    <option value="2022">2022</option>
                                    <option value="2023">2023</option>
                                    <option value="2024">2024</option>
                                </select>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal" style=" width 80px;">Đóng</button>
                                <input type="submit" class="btn btn-primary" value="Chọn" style="background-color: green;">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="agile-grids">
        <div class="index-slide-jobs">
            <div class="item-slide-job">
                <div class="lSSlideOuter ">
                    <div class="lSSlideWrapper usingCss">
                        <ul id="content-slider" class="content-slider lightSlider lsGrab lSSlide ul-slide-danh-sach-cong-viec">
                            @foreach (var item1 in ViewBag.ProjectMembers)
                            {
                                foreach (var item in ViewBag.listProject)
                                {
                                    if (item1.ProjectId == item.ProjectId)
                                    {
                                        <li class="li-slide-danh-sach-cong-viec" data-id="@item.ProjectId" onclick="ClickProject(this)">
                                            <div class="working-slide-item">
                                                <div class="working-slide-item-name">
                                                    <h3>@item.ProjectName</h3>
                                                </div>
                                                <div class="working-slide-item-time">
                                                    <span>Thời gian: </span>@item.StartTime.ToString("yyyy-MM-dd") - @item.EndTime.ToString("yyyy-MM-dd")
                                                </div>
                                                @*<div class="working-slide-item-progress">
                                                        <p><span>Tiến độ: </span>3/10</p>
                                                    </div>*@
                                            </div>
                                        </li>
                                    }
                                }
                            }
                        </ul><div class="lSAction"><a class="lSPrev"></a><a class="lSNext"></a></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="clearfix"> </div>
    </div>

    <div class="agile-bottom-grids">
        <!-- Phần này cho quy trình công việc -->
        <div id="progress-working" class="tbl-Statistical" style="background-color: transparent;">

        </div>
    </div>
</div>
@* Model Thông kê *@
<div id="modalDetailWork" class="modal">
    
</div>
@section scripts{
    <script>
        $("#content-slider").lightSlider({
            loop: true,
            keyPress: true
        });

        $('#image-gallery').lightSlider({
            gallery: true,
            item: 1,
            thumbItem: 9,
            slideMargin: 0,
            speed: 500,
            auto: true,
            loop: true,
            onSliderLoad: function () {
                $('#image-gallery').removeClass('cS-hidden');
            }
        });

        function loadListProject(e) {
            e.preventDefault();
            var month = $("#month").val();
            var year = $("#year").val();
            $.ajax({
                type: "POST",
                url: "@Url.Action("GetAllProjectByYearAndMonth","Statistical")",
                data: { month: month, year: year },
                success: function (rps) {
                    //$("#ModalAddNewWork").modal('toggle');
                    $(".agile-grids").html(rps);
                }
            });

        }
        function ClickProject(e) {
            var id = $(e).data("id");
            $.ajax({
                type: "POST",
                url: "@Url.Action("LoadListEmployeeByProject","Statistical")",
                data: { id: id },
                success: function (rps) {
                    $(".tbl-Statistical").html(rps);
                }
            });
        }

        function openModalDetailWork(e) {
            var ProjectId = $(e).data("id");
            var EmployeeId = $(e).data("content");
            var modalDetailWork = document.getElementById('modalDetailWork');
            var closeModalDetailWork = document.getElementsByClassName("closeModalDetailWork")[0];
            modalDetailWork.style.display = "block";
            $.ajax({
                type: "POST",
                url: "@Url.Action("LoadModelDetailWork","Statistical")",
                data: { ProjectId: ProjectId, EmployeeId: EmployeeId },
            success: function (rps) {
                $("#modalDetailWork").html(rps);
            }
        });
            //closeModalDetailWork.onclick = function () {
            //    modalDetailWork.style.display = "none";
            //}
            window.onclick = function (event) {
                if (event.target == modalDetailWork) {
                    modalDetailWork.style.display = "none";
                }
            }
        }
    </script>
}

QuanlyCV/Views/Statistical/LoadListEmployeeByProject.cshtml
<table class="table table-hover table-bordered">
    <thead>
        <tr style="color: #fff">
            <th>Người Tạo Công Việc</th>
            <th>Phòng Ban</th>
            <th>Giao Cho </th>
            <th></th>
        </tr>
    </thead>
    <tbody class="table-body">
        @foreach (var item in ViewBag.listEmployeeByProjectId)
        {
            <tr class="text-center" style="color: #00bcd4">
                @foreach (var item1 in ViewBag.listEmployeeByRoleId)
                {
                    <td>@item1.EmployeeFullname</td>
                }
                <td>@item.DepartmentName</td>
                <td>@item.EmployeeFullname</td>
                <td>
                    <a onclick="openModalDetailWork(this)" data-id="@item.ProjectId" data-content="@item.EmployeeId" style="color:#00bcd4">Chi Tiết</a>
                </td>
            </tr>
        }
    </tbody>
</table>

QuanlyCV/Views/Statistical/LoadModelDetailWork.cshtml
@foreach (var item in ViewBag.DetailEmployeeByWork)
{
    <div class="modal-content">
        @*<span class="closeModalDetailWork">&times;</span>*@
        <br />
        <br />
        <div class="text-center" style="width: 100%"><b style="color: #eb5a46">Chi Tiết Công Viêc:</b></div>
        <form>
            <div class="subdiv-modal-chi-tiet">
                <span class="span-subdiv-modal-chi-tiet">Tên Công Viêc:</span>
                <input type="text" name="ProjectName" id="ProjectName" value="@item.ProjectName" class="input-subdiv-modal-chi-tiet" />
            </div>
            <div class="subdiv-modal-chi-tiet">
                <span class="span-subdiv-modal-chi-tiet">Người Thực Hiện:</span>
                <input type="text" name="EmployeeFullname" id="EmployeeFullname" value="@item.EmployeeFullname" class="input-subdiv-modal-chi-tiet" />
            </div>
            <div class="subdiv-modal-chi-tiet">
                <span class="span-subdiv-modal-chi-tiet">Phòng Ban:</span>
                <input type="text" name="DepartmentName" id="DepartmentName" value="@item.DepartmentName" class="input-subdiv-modal-chi-tiet" />
            </div>
            <div class="subdiv-modal-chi-tiet">
                <span class="span-subdiv-modal-chi-tiet">Chức Vụ</span>
                <input type="text" name="RoleName" id="RoleName" value="@item.RoleName" class="input-subdiv-modal-chi-tiet" />
            </div>
            <div class="subdiv-modal-chi-tiet">
                <span class="span-subdiv-modal-chi-tiet">Kiểu Dự Án</span>
                <input type="text" name="ProjectTypeName" id="ProjectTypeName" value="@item.ProjectTypeName" class="input-subdiv-modal-chi-tiet" />
            </div>
            @*<div style="width: 100%">
                <input type="Submit" name="" value="Lưu" class="inputsubmit-subdiv-modal-chi-tiet">
            </div>*@
        </form>
    </div>
}